name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # install deps and build
      - run: npm ci
      - run: npm run build

      # determine output dir (Vite uses dist). Also add SPA fallback.
      - name: Prepare artifact
        id: out
        run: |
          OUT="dist"
          if [ ! -d "$OUT" ]; then
            echo "dist not found"; exit 1
          fi
          cp "$OUT/index.html" "$OUT/404.html" || true
          echo "outdir=$OUT" >> $GITHUB_OUTPUT

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.out.outputs.outdir }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
